# Zalewski's place

As it turned out, the only one of us that Caleb Shivers tied up was Fulton Gully. Randall Wragge moved the horse van behind the barn so that it couldn't be seen from the driveway. The van moved in stops and starts and I saw, then, why Randall Wragge preferred horses. He came back glowering and the five of us went inside the barn.

Caleb Shivers pushed Fulton Gully onto a hay bale against the far wall. Then he slid his head back and forth, looking first at me and Willie and, then, at his and Randall Wragge's horses. The animals were tied into Chips' stall, eating from their feed bags. He looked between us and the horses one last time, but with more *meaning*, and finished up with his head tilted to one side, eyes wide open in my direction.

Randall Wragge sighed. "Caleb, maybe the reason you get so hungry is you ain't worked out what your mouth *does* yet. What stops you being polite and just asking the boy?"

Caleb Shivers stopped looking at me and turned to Randall Wragge. "I know what using my mouth and being polite gets me, Randall. How many times I need to say it? How can you get told?"

Randall Wragge sighed again and shook his head. From their manner, I guessed that this quarrelling was normal, rather than them getting ready to shoot each other. "Lucky Joe", he said, "a barn ain't a barn without food. That horse of your's must have enjoyed his hay in here. Least"—and he looked at Fulton Gully and pointed a finger up to the roof—"until your daddy sent him to that *other* stable. So that agreement we made covers you fixing us a meal, don't it?"

That sparked something in me, but I held back my anger. "We ain't going to let a guest starve", I said, stony-voiced.

Randall Wragge sighed again. "I insulted Oklahoma before you came on out", he said to Caleb Shivers, as if that explained things. "Don't be sore on that, Lucky Joe. What did this State ever do for you, anyhow? Seems like your soil ain't fit for a graveyard and most of what you earn, that fellow"—and now he directed his finger at Fulton Gully—"ends up wearing".

"Or eating", Caleb Shivers said.

"Okay, Caleb", Randall Wragge said and he fair spat the words.

"We'll both go", I said and I gestured for Willie, who had been looking bemused this whole time, to follow me.

"Hurry back now", Randall Wragge said.

"And just because I have to sleep like an animal, it doesn't mean I want to eat like one", Caleb Shivers said.

As I shut the barn door, I could see that they'd already come together and started whispering out of Fulton Gully's earshot.

When we were out of the barn, Willie was jumping from foot to foot and desperate to talk, but I shushed him until we were a good distance down the driveway.

"Why'd that man say he was going to sleep here?", Willie said, when I let him speak.

"Just for one night", I said. "To help us. We owe Mr Gully a heap of money, Willie, and we don't have it. They'll help us get it."

"Sleep in a barn", Willie said, with scorn. And then he added, as if the fearful thought had just grabbed him, "Will they shoot Midnight Runner?"

"No", I said, and then I stopped him on the track by taking hold of his elbow. "Look, why are you even *here*? I told you to go to school".

"You told me Dad was drinking at home", Willie said, and he wrenched his elbow away from me in anger. "But *Pete* said he saw him go into Zalewski's place. He'll be asleep in there by now, Joe."

Well, I didn't like that news. I'd thought that Dad was headed into town to sell the horse meat, and that it would take him a good couple of days to spend the proceeds. But if he'd found a way to lose the meat, or lose the money, closer to home, then he'd be back by the evening. If Dad was headed back, then I'd need to get rid of Randall Wragge and Caleb Shivers much quicker than I'd planned. And, truthfully, now that Caleb Shivers had turned up, I had no idea how to rid of the both of them, fast or slow.

"You know what else Pete saw, out at Zalewski's?", Willie said.

"What?", I said.

"A dog", Willie said, "Only, it was sat out on the porch, playing cards. And it was winning, Joe."

"Zalewski doesn't have a porch", I said, "People would fall off it".

***

The kitchen was empty when we got back to the house. The place seemed hollow somehow, with just the two of us breaking into the silence, and the dust floating in the sunlight. Willie found some biscuits and gravy and got to heating them up.

I left Willie there, humming to himself by the stove, and I went through to the unlit den next door. Normally I'd have just skirted around the doorway because this was Dad's room. The place smelt of evaporating alcohol and of the chair that Dad sat in while he had his sweats. I wrinkled my nose against the smell, but I knew what I was after: the chest that stood against the right-hand wall. As I approached, it was like Dad had sat down in the chair behind me. I felt his eyes creeping down my spine—brooding or furious, we never could tell—and I couldn't stop thinking he was *there* until my hands were on the catch and lifting the lid, and I knew for sure what something real felt like.  

Dad kept a pistol in the chest; I'd seen him sit there in the dark, turning the gun between his fingers. I didn't know if the pistol would fire, since I'd never seen him use it, or clean it. But it was better than nothing and, unlike the shotgun, I could get it up to the barn without Randall Wragge and Caleb Shivers seeing. Sure enough, I found the pistol underneath a lot of other junk: a garrison cap like the one Caleb Shivers wore, a broken kerosene lamp, the head of a hand axe, a folder of curling photographs. When I pulled the box out, my hands were somehow black with oil. Just as I was about to pull the pistol out and inspect it, there was a sharp rapping from the wall next to me and, startled, I lost my grip on the box and the bullets inside scattered onto the hard floor.

"Joe?", I heard Willie call out, and his voice was quiet and urgent, so I knew that he'd had the same thought as me: that Dad was back already.

The smell of Dad's body seemed to rise up from the chair and choke me, and when I twisted around, my foot sent the bullets scattering off along the hard floor. The noise was like a rattle of footsteps and the den was so dark that, when I turned back towards the door, I was half-blinded by the light coming from the kitchen.

"Joe", Willie said again, "what's happening?" He sounded scared, but I didn't want to answer in case Dad found me trying to steal his gun. I tried to creep as silently as I could towards the doorway.  There was a few seconds of silence, and the rapping started again—weaker this time, but still urgent-sounding. And, then I realised what the noise was, and I relaxed and walked straight to the kitchen doorway.

"What is it, Joe?", Willie said, turning round to me. He looked like he might cry.

"Mama's awake", I said, "That's all".

"Oh", Willie said, lightening up, "Can I go and see her?"

"Sure", I said, "Take her some of those biscuits".

"You coming to say hello, Joe?", Willie said.

I looked at the box in my hand, and thought about the rapping on the wall.

"No", I said, "I ain't got time for that".

***

I had the pistol tucked out of sight, inside my belt and under my shirt, as we walked back towards the barn. Willie was singing to himself, like always when he'd seen Mama. He was a couple of paces ahead of me and I could hear the words filter back: "I've a Father on the road, He's almost done travelling, A Father on the road." I never sang—something stopped the sound coming out of me—but I liked to hear Willie making a racket anyhow.

I felt easier on the way back because I'd an idea, now, of how to get rid of Randall Wragge and Caleb Shivers. I knew there was a phone up at Fulton Gully's place, because I'd stood on his doorstep a time or two, waiting for him to finish talking on it. And I knew that his place was empty, because Fulton Gully was stuck here with *us*. If Willie could get away—say, if I sent him back with the used dishes so that Caleb Shivers didn't have to suffer a filthy barn—then he could slip up the road and alert the authorities. The more I thought about the plan, the more I liked it, because Randall Wragge and Caleb Shivers were sure to have some kind of reward on their heads, and I could use that money to pay Fulton Gully for Chips. If Fulton Gully still thought I was in on the deal, I could say that Randall Wragge had his gun on me, which was true enough. And, if things went bad, I'd have a pistol stashed nearby to get me and Willie clear.    

When we came in sight of the barn, Caleb Shivers was leaning up against its near corner, smoking a cigarette. He saw us, pushed off from the wall with his foot and threw the butt onto the floor. He nodded, turned and started to walk back towards the barn doors. I gestured at Willie to follow Caleb Shivers, but I veered off to the other side of the driveway. I'd made up my mind to hide the pistol by the water well. I wanted the pistol close but I figured the quickest way to get killed was would be to have Randall Wragge find a gun on me. The well was a good spot for it, too. There were enough old rocks at the base that I could make a pile and stash the gun without it being obvious, and I'd have good reason to go out there and fetch it back.

I reached the well and let off the handle to drop the bucket. The rope unspooled with a soft whistle and I pushed at a few likely rocks with my foot while the bucket fell. But the well was a long drop and the rusting windlass began to grate just as Caleb Shivers was about to open the barn door—and the noise of it made him turn around.

"What are you doing, Joe?", Caleb Shivers said. There wasn't any threat about his voice, but that calmness somehow made it worse.

"Pulling some water", I said. "We'll want some. The food's awful salty".

"It isn't", said Willie.

"Leave it alone", Caleb Shivers said, and there wasn't room in his tone for an argument. "We'll make a fire and brew some coffee when we've eaten".

Willie made a face, like this was the worst thing he'd heard in the last two days.

I came away from the well. Caleb Shivers watched me walk back towards him and I could feel the pistol in my waistband the whole time. But I thought that Caleb Shivers couldn't be watching me too closely because he was also talking. "Coffee and cigarettes—that's how you control hunger. Politeness", Caleb Shivers said, before finally pushing open the barn door, "has got nothing to do with it. You boys should try it, starving out here on your little farm".

The three of us walked inside.

"Think you could help us grow tobacco, then?", Willie said, "For the cigarettes?"

Caleb Shivers stopped dead and stared at Randall Wragge.

"He ain't *my* brother", Randall Wragge said.

And then Caleb Shivers pivoted to stare dead at me. "Your boy going to ask me to cut sugarcane next?", he said.

"No, sir", I said.

"We can get sugar from Mr Gully", Willie said, "To give to Midnight Runner".

We all looked over at Fulton Gully and that was the first time, I think, that Willie realised what was really happening—because Randall Wragge and Caleb Shivers had worked Fulton Gully over while we'd been away, and he was sitting there looking bloody and dazed. Willie looked straight to me, confused, but there wasn't anything I could tell him.

"All that talk", Randall Wragge said to Fulton Gully, "and you never told us, you'd been mistreating that horse, Mr Gully. Horse like that only ever has a custodian, but what kind of custodian poisons his charge with sugar? Matter of fact, the *new* custodian might not want it known that the *old* custodian had that horse on a bad diet."

Caleb Shivers looked at Randall Wragge, who nodded—and with two quick paces, Caleb Shivers was right next to me. Before I knew what was happening, Caleb Shivers had pulled up my shirt, lifted the pistol from my waistband and, in one smooth movement, he turned and shot Fulton Gully through the chest.

I could hardly hear anything except the ringing in my ears, but I knew that Willie had started to cry. Caleb Shivers had a hold of my elbow and Randall Wragge was coming in close. The barn seemed to be vibrating. Fulton Gully's body appeared, in the stripes between the jostling of Randall Wragge and Caleb Shivers. But then things seemed to clear. I could hear again, and Willie *was* crying, but softly, as if he was hoping to be forgotten. And Randall Wragge and Caleb Shivers seemed to back off, and the thing that confused me the most—Caleb Shivers dropped hold of my elbow, and handed me the gun back.

I looked down at the pistol in my hand, then up at Fulton Gully. The blood was spreading across his white shirt and it was like he'd put his purple jacket back on to die. This whole time, I'd been thinking about the money that we owed Fulton Gully for Chips, but that wasn't the same thing as giving him the money back—not the same thing at all.

The pistol felt hot and heavy in my hand.

"Well, you in this pretty deep now, ain't you, boy?", Caleb Shivers said.